# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build iOS app without code signing"
  lane :build_ios do
    build_app(
      scheme: "Runner",
      workspace: "ios/Runner.xcworkspace",
      export_method: "development",
      export_options: {
        method: "development",
        uploadBitcode: false,
        uploadSymbols: true,
        compileBitcode: false
      }
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    build_ios
    # upload_to_testflight
  end
end
