name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest'
        
    - name: Debug - List directory contents
      run: |
        echo "=== Root directory ==="
        ls -la
        echo "=== centro_emprendedores_app directory ==="
        ls -la centro_emprendedores_app/
        echo "=== pubspec.yaml exists? ==="
        ls -la centro_emprendedores_app/pubspec.yaml
        
    - name: Install dependencies
      run: |
        cd centro_emprendedores_app
        echo "=== Current directory ==="
        pwd
        echo "=== Flutter doctor ==="
        flutter doctor -v
        echo "=== Flutter pub get ==="
        flutter pub get --verbose
