name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest'
        
    - name: Install dependencies
      run: |
        cd centro_emprendedores_app
        flutter pub get --verbose
        
    - name: Build iOS (no codesign)
      run: |
        cd centro_emprendedores_app
        flutter build ios --release --no-codesign
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: centro_emprendedores_app/build/ios/Release-iphoneos/
