name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
        
    - name: Install dependencies
      run: |
        cd centro_emprendedores_app
        flutter pub get
        
    - name: Run Flutter analyze
      run: |
        cd centro_emprendedores_app
        flutter analyze
        
    - name: Run Flutter test
      run: |
        cd centro_emprendedores_app
        flutter test
        
    - name: Build iOS (no codesign)
      run: |
        cd centro_emprendedores_app
        flutter build ios --release --no-codesign
        
    - name: Create IPA
      run: |
        cd centro_emprendedores_app
        mkdir -p build/ios/ipa
        xcodebuild -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath build/ios/archive/Runner.xcarchive \
          archive
        xcodebuild -exportArchive \
          -archivePath build/ios/archive/Runner.xcarchive \
          -exportPath build/ios/ipa \
          -exportOptionsPlist ios/ExportOptions.plist
          
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v3
      with:
        name: ios-ipa
        path: centro_emprendedores_app/build/ios/ipa/*.ipa
